### ISSUE TITLE
additionalPropertiesのサポート

### ISSUE THREAD

**Issue by yoshi6jp** [aspidajs/aspida#381]
## Description

- https://swagger.io/docs/specification/data-models/dictionaries/

## Describe the solution you'd like

https://github.com/aspidajs/aspida/blob/master/packages/openapi2aspida/samples/swagger.yaml#L307
swagger.yaml
```yaml
 /store/inventory:
    get:
      tags:
      - "store"
      summary: "Returns pet inventories by status"
      description: "Returns a map of status codes to quantities"
      operationId: "getInventory"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
      security:
      - api_key: []
```
https://github.com/aspidajs/aspida/blob/master/packages/openapi2aspida/samples/swagger/store/inventory.ts#L4

inventory.ts (期待値)
```ts
/* eslint-disable */
import { mockMethods } from 'aspida-mock'
export type Methods = {
  get: {
    resBody: {[key:string]:number}
  }
}

export default mockMethods<Methods>({
  get: () => ({ status: 200, resBody:{"a":1} })
})

```

**Comment by m-mitsuhide** [comment]
@yoshi6jp 

Issue投稿ありがとうございます
初期実装時にadditionalPropertiesよくわからんなーと無視していたことを思い出しました・・・
提案いただいた通りに修正し、openapi2aspida@0.5.3をリリースしました

出力結果はこちらです
https://github.com/aspidajs/aspida/blob/master/packages/openapi2aspida/samples/swagger/store/inventory.ts

aspidaの改善にご協力いただきありがとうございました！
