### ISSUE TITLE
ApiClientコード生成に必要な情報を整理する

### ISSUE THREAD

**Issue by tooppoo** [aspidajs/aspida#41]
## Description

現在のコード生成実装をリファクタするにあたり
- コード生成に必要な情報は何か
- コード生成に必要な情報はどのような構造か

を整理/モデル化する。

api定義のtsファイル
↓
ApiClientコードモデル
↓
templateにモデルの情報を埋め込み
↓
clientコード生成

という流れを想定。

**Comment by tooppoo** [comment]
```uml
@startuml Aspida AST
package Method {
  interface Method {
    name: string
  }
  package Argument {
    interface Data {
      name: string
      type: string
    }
    interface Query {
      name: string
      type: string
    }
  }

  interface SuccessResponsetype {
    name: string
  }
  interface ErrorResponseType {
    name: string
  }

  Method *--> "0..n" Query
  Method *--> "0..n" Data
  Method *--> "1" SuccessResponsetype
  Method *--> "1" ErrorResponseType
}

package ApiClient {
  interface ApiClientModel {
    name: string
    path: string
  }

  interface Import {
    alias: string
    target: ApiClientModel
  }
  ApiClientModel *------> "0..n" Import : children
  Import *-right-> "1" ApiClientModel
}
ApiClientModel *--> "0..n" Method

note bottom of Query
クエリパラメータ.現実装では"params"として表現?
axiosのIFに引っ張られている感が有るので、
命名変えた方が良さそうな印象.
end note
@enduml
```

**Comment by m-mitsuhide** [comment]
私の知識不足で詳細把握しきれていない部分はありますが、現状の場当たりな実装よりは遥かに整理されている図であることは理解できました
異論はないのでこのモデルに沿ってリファクタリングを進めましょう

axiosの命名に引っ張られて「params」としたのはその通りです
mockにも影響ある部分なので早めにqueryに変えたい

異常系とレスポンスヘッダーが現実装で考慮出来てなくてどうすべきか悩んでました
これも上記の案で改善できそう

**Comment by tooppoo** [comment]
了解です、確認ありがとうございます 🙇 
ざっくり、aspida内部でコード生成するにあたって前提としている知識/情報を端的に表現できていること見て頂ければ、細かいところは気にしないで良いと思います（自分も雰囲気でUML書いてるのでw）
細かい仕様や設計の確認というより、大まかな全体イメージの共有に利用していただければと思います。

リファクタリングについて、一気にここまで持っていこうとすると巨大なPRになりそうなので、いくつか細かく分けてだそうと思います。
直近は
1. params → queryの変更 (breaking changeなので、リリースノートなりで明記必要？）
1. ↑のモデルに従ったオブジェクトツリー実装
1. compiler api から取得したAST → ↑のaspida用オブジェクトツリーへの変換実装
1. aspida用オブジェクトツリーから、コードを出力する仕組みの実装
  - compiler API、plop、テンプレートリテラル どれを使うかは、このタイミングで検討
1. 既存実装から↑の仕組みへの置き換え

のスケジュールで進めようかなと思います。

**Comment by tooppoo** [comment]
> 異常系とレスポンスヘッダー

レスポンスヘッダーについて抜けてましたね。追記 + Query/Dataについて「aspidaで取り扱う型定義情報」であって、具体的な型定義を取り扱うわけではないという表明として `Type` をsuffix的に追加しました。
![Aspida AST](https://user-images.githubusercontent.com/10760022/67643090-942d2100-f956-11e9-9f98-350415b68519.png)

この図ですが、 plantUMLというツールで記述しているので実体はテキストです。
issueだけに残すより、aspidaの設計ドキュメントとしてgitに載せておいた方が良いのかなぁと思ったりするのですが、その辺りいかがでしょうか？

**Comment by m-mitsuhide** [comment]
breaking changeは以下のルールでコミットしてもらえればOKです
https://bit.ly/2NjOaiS

進行スケジュールもいいですね、PRの内容を理解できるよう頑張ります

確かにこの見た目plantUMLですね、相当昔にちょっと触ってたはずなのにすっかり忘れてました・・・
GitHubのWikiに上げたいけどテキスト⇒画像変換をGitHubがしてくれないから通常のリポジトリ管理にして各自VSCodeに拡張入れるのがいいかな
docsか、あまり見ないけどblueprintsディレクトリを作って管理しましょうか

**Comment by m-mitsuhide** [comment]
リリースノートへのbreaking changeの記述はstandard-versionがコミット内容から自動生成するCHANGELOGから私が転記しておくので作業不要です

**Comment by tooppoo** [comment]
@m-mitsuhide 
リファクタリングに手を出しはじめてみたんですが、
> params → queryの変更 (breaking changeなので、リリースノートなりで明記必要？）

について、こちら現在は「入力として定義されている型」と「出力で使われる型」が同じものであるため、「入力として定義されている型」の名前を変えてしまうと、出力される型も変わってしまう = axiosが求める型と一致せず、Type Errorになってしまうようです。
即ち、現実装は入力の構造がaxiosに依存したものとなっているため、リファクタをかけてaspida用のASTを間にはさみ、axiosへの直接依存を排除してからパラメータ名変更を行うようにした方が良さそうです。

上の理由から、
1. ↑のモデルに従ったオブジェクトツリー実装
2. compiler api から取得したAST → ↑のaspida用オブジェクトツリーへの変換実装
3. aspida用オブジェクトツリーから、コードを出力する仕組みの実装
    - compiler API、plop、テンプレートリテラル どれを使うかは、このタイミングで検討
4. 既存実装から↑の仕組みへの置き換え
5. params → queryの変更 (breaking changeなので、リリースノートなりで明記必要？）

の順での対応に変更します。

**Comment by m-mitsuhide** [comment]
言われてみれば！
入力値の型がaxios依存ですね・・・
ORMみたいに各クライアントのドライバー読み込めばaxios/ky/superagentとかに対応できるようになる未来を見据えた標準化された入力値を定義したいですね

もう一点、axiosに大きく引っ張られている仕様として、deleteメソッドでdataを送信する場合はparams/headersと同様のconfigオブジェクトに含めるようになってます
参考：https://qiita.com/yfujii1127/items/991ae9ff29b478a55b1c#%E8%AA%BF%E3%81%B9%E3%81%A6%E3%81%BF%E3%82%8B%E3%81%A8

kyみたいにoptionsに統合するのも一案かなと思います
グローバルなOSSで採用されている形式に則っていれば実装しながら決めてもらってOKです
今はユーザーが少ないので大きな変更があっても個別にマイグレーションのサポートしていきます

**Comment by m-mitsuhide** [comment]
アーキテクチャが大幅にアップデートされたので必要があれば新たなチケットで設計の見直しを行う
