### ISSUE TITLE
--versionが間違った値を返す

### ISSUE THREAD

**Issue by ibuki2003** [aspidajs/aspida#415]
## Description

```sh
yarn aspida --version
```
を実行するとaspidaではなくカレントディレクトリのpackage.jsonのバージョンが表示されてしまいます

## Environment

- **Package version:**
  
  `v0.15.2`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v14.1.0`
- **npm version:**
  
  `6.14.4`

**Comment by m-mitsuhide** [comment]
@ibuki2003 

バグ報告ありがとうございます
プロジェクトのディレクトリでversionコマンドを叩いたことがなくて全く気が付きませんでした・・・

修正とnpmへのリリースが完了しました
クライアントにaxiosを使っている場合は`@aspida/axios@0.5.3`にアップデートしてください

aspidaの改善にご協力いただきありがとうございました！
