### ISSUE TITLE
特殊記号が含まれるパスを定義できない

### ISSUE THREAD

**Issue by su8ru** [aspidajs/aspida#462]
## Description

Windows 環境において、パスに `:`などのファイル名に使えない記号 が含まれる場合、パスを定義できません。

aspida が原因にあるわけではないのですが、ご検討いただけると嬉しいです。

## Describe the solution you'd like

Vue スタイルでのパス定義も書けるようにすると、パスを string で定義できるので解決できそうです。

## Additional context

Ubuntu でファイルの作成はできます。
![image](https://user-images.githubusercontent.com/33474143/85088838-fc00e680-b21b-11ea-88aa-d778b781e154.png)

Windows から見ると悲惨な状況です…
![image](https://user-images.githubusercontent.com/33474143/85088911-1b980f00-b21c-11ea-9a1a-9f1a9f42e711.png)

ビルド・実行は Ubuntu 上で行うので問題ありませんが、`$api.ts` を Windows 側で見ると参照できずにエラーが出てしまいます。
![image](https://user-images.githubusercontent.com/33474143/85088936-3074a280-b21c-11ea-9d56-e878d3261dfa.png)

## Environment

- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [ ] macOS

**Comment by solufa** [comment]
@su8ru 
Issue投稿ありがとうございます
最終的な目的は以下サイトのAPIをaspidaで定義してLinux/Winともに正常動作することだと認識いたしました
https://www.odpt.org/

現在アカウント登録審査待ちです
Tokenが発行され次第、どんな方法で実装するか検討いたします
ファイル名として使えない文字の対応要望もいずれは来るだろうなと予測していたので良い機会でした
お待ちください

**Comment by solufa** [comment]
@su8ru 
解決策が見つかりました
特殊記号はURLエンコードすると動作します
「:」はURLエンコードすると「%3A」なのでディレクトリ名を「odpt%3A~~」にしてください
クライアントからは「_3A」でアクセスできます

Win10での検証結果
![odpt](https://user-images.githubusercontent.com/9402912/85101753-1c419d00-b23e-11ea-9f79-ad44818d0314.png)

今回の検証で有益なTipsと、軽微なバグを発見できました
（このIssueには影響がないバグなので修正リリースを待つ必要はありません）

今後も気付いた点あればお気軽にIssue投稿していただけると非常に助かります
aspidaの改善にご協力いただきありがとうございました！

**Comment by su8ru** [comment]
この発想はありませんでした！
ありがとうございます！

いつも便利で助かっています。
これからもよろしくお願いします！
